# Copyright 2021 David Ames
# See LICENSE file for licensing details.

options:
  minimum-replicas:
    default: 3
    description: Minimum number of queues replicas, set to 0 to disable charm automatically managing queue replicas
    type: int
  auto-ha-frequency:
    default: 30
    description: Frequency in minutes to check for queues that need HA members added
    type: int
