name: deploy

on:
  workflow_call:


jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.26-strict/stable
          juju-channel: 3.1/stable
          microk8s-addons: hostpath-storage dns rbac metallb:10.64.140.40-10.64.140.49
      - name: Install dependencies
        run: |
          sudo snap install --classic terraform
          sudo snap install --classic juju-wait
